---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-pages-wildcard
  namespace: gitlab-system
spec:
  dnsNames:
    - "*.pages.sentracam.net"
  secretName: gitlab-pages-wildcard
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
---
